import { TaskStage, TaskTheme } from '@prisma/client';

export type CatalogTask = {
  id: string;
  title: string;
  description: string;
  section: string;
  stage: TaskStage;
  theme: TaskTheme;
  order: number;
  xpReward: number;
};

export type CatalogAchievement = {
  id: string;
  name: string;
  description: string;
  icon: string;
  xpReward: number;
  unlockRule: string;
};

export const taskCatalog: CatalogTask[] = [
  {
    id: 'gather-wood-craft-tools',
    title: 'Gather wood and craft tools',
    description: 'Secure logs, craft a crafting table, and build your first toolkit.',
    section: 'Survival Basics',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 1,
    xpReward: 30,
  },
  {
    id: 'build-shelter',
    title: 'Build shelter',
    description: 'Create a safe first-night structure with room to grow.',
    section: 'Survival Basics',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 2,
    xpReward: 25,
  },
  {
    id: 'make-bed',
    title: 'Make bed',
    description: 'Set a respawn point and skip hostile nights when needed.',
    section: 'Survival Basics',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 3,
    xpReward: 20,
  },
  {
    id: 'get-food',
    title: 'Get food',
    description: 'Stabilize hunger with early hunting, crops, or fishing.',
    section: 'Survival Basics',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 4,
    xpReward: 20,
  },
  {
    id: 'craft-furnace-torches',
    title: 'Craft furnace & torches',
    description: 'Light your surroundings and prepare for caving.',
    section: 'Survival Basics',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 5,
    xpReward: 20,
  },
  {
    id: 'build-starter-house',
    title: 'Build starter house',
    description: 'Upgrade from a survival box to a dependable base.',
    section: 'Base Building',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 6,
    xpReward: 25,
  },
  {
    id: 'organize-storage',
    title: 'Organize storage',
    description: 'Set up labeled storage for smoother long-term progression.',
    section: 'Base Building',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 7,
    xpReward: 15,
  },
  {
    id: 'light-up-area',
    title: 'Light up area',
    description: 'Prevent mob spawns and secure the perimeter around your base.',
    section: 'Base Building',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 8,
    xpReward: 20,
  },
  {
    id: 'wheat-farm',
    title: 'Wheat farm',
    description: 'Start a renewable food loop for consistency.',
    section: 'Food & Farming',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 9,
    xpReward: 20,
  },
  {
    id: 'animal-farm',
    title: 'Animal farm',
    description: 'Breed animals to support food, leather, and utility needs.',
    section: 'Food & Farming',
    stage: TaskStage.BEGINNER,
    theme: TaskTheme.OVERWORLD,
    order: 10,
    xpReward: 25,
  },
  {
    id: 'crop-expansion',
    title: 'Crop expansion',
    description: 'Scale farms to support trading, breeding, and brewing.',
    section: 'Food & Farming',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 11,
    xpReward: 20,
  },
  {
    id: 'mine-iron',
    title: 'Mine iron',
    description: 'Gather iron for your first major equipment jump.',
    section: 'Iron Progression',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 12,
    xpReward: 25,
  },
  {
    id: 'craft-iron-gear',
    title: 'Craft iron gear',
    description: 'Upgrade armor and tools for more dangerous ventures.',
    section: 'Iron Progression',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 13,
    xpReward: 30,
  },
  {
    id: 'craft-shield',
    title: 'Craft shield',
    description: 'Add a crucial defensive tool before deeper exploration.',
    section: 'Iron Progression',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 14,
    xpReward: 20,
  },
  {
    id: 'explore-biomes',
    title: 'Explore biomes',
    description: 'Locate diverse resources and future build inspiration.',
    section: 'Exploration',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 15,
    xpReward: 20,
  },
  {
    id: 'find-village',
    title: 'Find village',
    description: 'Unlock beds, crops, trading, and villager progression.',
    section: 'Exploration',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 16,
    xpReward: 30,
  },
  {
    id: 'create-map',
    title: 'Create map',
    description: 'Track your world and organize routes between major landmarks.',
    section: 'Exploration',
    stage: TaskStage.MID_GAME,
    theme: TaskTheme.OVERWORLD,
    order: 17,
    xpReward: 15,
  },
  {
    id: 'mine-diamonds',
    title: 'Mine diamonds',
    description: 'Unlock top-tier tools and your path into the Nether.',
    section: 'Diamond Stage',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 18,
    xpReward: 40,
  },
  {
    id: 'craft-diamond-tools',
    title: 'Craft diamond tools',
    description: 'Maximize mining and combat efficiency for tougher milestones.',
    section: 'Diamond Stage',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 19,
    xpReward: 35,
  },
  {
    id: 'collect-obsidian',
    title: 'Collect obsidian',
    description: 'Gather what you need for portals and later enchanting.',
    section: 'Diamond Stage',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 20,
    xpReward: 30,
  },
  {
    id: 'enchanting-table',
    title: 'Enchanting table',
    description: 'Build your core gear progression station.',
    section: 'Enchanting',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 21,
    xpReward: 35,
  },
  {
    id: 'bookshelves',
    title: 'Bookshelves',
    description: 'Push your enchanting setup toward top-tier outcomes.',
    section: 'Enchanting',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 22,
    xpReward: 25,
  },
  {
    id: 'gain-xp',
    title: 'Gain XP',
    description: 'Secure enough experience to roll powerful enchants.',
    section: 'Enchanting',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.OVERWORLD,
    order: 23,
    xpReward: 25,
  },
  {
    id: 'build-portal',
    title: 'Build portal',
    description: 'Open the gateway to blaze rods, wart, and new materials.',
    section: 'Nether Progression',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.NETHER,
    order: 24,
    xpReward: 40,
  },
  {
    id: 'find-fortress',
    title: 'Find fortress',
    description: 'Locate the structure that unlocks End preparation.',
    section: 'Nether Progression',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.NETHER,
    order: 25,
    xpReward: 40,
  },
  {
    id: 'collect-blaze-rods-nether-wart',
    title: 'Collect blaze rods & nether wart',
    description: 'Gather the essentials for brewing and Eyes of Ender.',
    section: 'Nether Progression',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.NETHER,
    order: 26,
    xpReward: 45,
  },
  {
    id: 'brewing-stand',
    title: 'Brewing stand',
    description: 'Craft your potion lab and prepare for specialized buffs.',
    section: 'Brewing',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.NETHER,
    order: 27,
    xpReward: 25,
  },
  {
    id: 'basic-potions',
    title: 'Basic potions',
    description: 'Brew foundational potions for survivability and combat.',
    section: 'Brewing',
    stage: TaskStage.ADVANCED,
    theme: TaskTheme.NETHER,
    order: 28,
    xpReward: 25,
  },
  {
    id: 'ender-pearls',
    title: 'Ender pearls',
    description: 'Collect pearls from Endermen to power your End journey.',
    section: 'End Preparation',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 29,
    xpReward: 35,
  },
  {
    id: 'eyes-of-ender',
    title: 'Eyes of Ender',
    description: 'Combine blaze powder and pearls to locate the stronghold.',
    section: 'End Preparation',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 30,
    xpReward: 35,
  },
  {
    id: 'find-stronghold',
    title: 'Find stronghold',
    description: 'Reach the portal room and ready your final supplies.',
    section: 'End Preparation',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 31,
    xpReward: 40,
  },
  {
    id: 'destroy-crystals',
    title: 'Destroy crystals',
    description: 'Handle the End towers to neutralize dragon healing.',
    section: 'Ender Dragon',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 32,
    xpReward: 45,
  },
  {
    id: 'defeat-dragon',
    title: 'Defeat dragon',
    description: 'Finish the main survival arc and unlock outer End access.',
    section: 'Ender Dragon',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 33,
    xpReward: 80,
  },
  {
    id: 'find-end-city',
    title: 'Find End City',
    description: 'Search the outer islands for rare structures and loot.',
    section: 'End Game Loot',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 34,
    xpReward: 45,
  },
  {
    id: 'get-elytra',
    title: 'Get Elytra',
    description: 'Claim the movement upgrade that changes long-distance play.',
    section: 'End Game Loot',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 35,
    xpReward: 60,
  },
  {
    id: 'get-shulker-boxes',
    title: 'Get Shulker Boxes',
    description: 'Unlock highly portable storage for major projects.',
    section: 'End Game Loot',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.END,
    order: 36,
    xpReward: 45,
  },
  {
    id: 'mega-base',
    title: 'Mega base',
    description: 'Scale from survival shelter to signature world project.',
    section: 'Late Game',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.OVERWORLD,
    order: 37,
    xpReward: 50,
  },
  {
    id: 'villager-trading-hall',
    title: 'Villager trading hall',
    description: 'Create a high-efficiency economy for enchants and gear.',
    section: 'Late Game',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.OVERWORLD,
    order: 38,
    xpReward: 50,
  },
  {
    id: 'automatic-farms',
    title: 'Automatic farms',
    description: 'Automate key resources to support endgame building.',
    section: 'Late Game',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.OVERWORLD,
    order: 39,
    xpReward: 55,
  },
  {
    id: 'beacon',
    title: 'Beacon',
    description: 'Claim one of survival mode’s defining prestige utilities.',
    section: 'Late Game',
    stage: TaskStage.ENDGAME,
    theme: TaskTheme.OVERWORLD,
    order: 40,
    xpReward: 65,
  },
];

export const achievementCatalog: CatalogAchievement[] = [
  {
    id: 'first-night-survivor',
    name: 'First Night Survivor',
    description: 'Complete your first five early survival tasks.',
    icon: 'MoonStar',
    xpReward: 50,
    unlockRule: 'complete_5_tasks',
  },
  {
    id: 'iron-age',
    name: 'Iron Age',
    description: 'Complete the full Iron Progression section.',
    icon: 'Shield',
    xpReward: 80,
    unlockRule: 'complete_section:Iron Progression',
  },
  {
    id: 'diamond-hunter',
    name: 'Diamond Hunter',
    description: 'Reach and complete the Diamond Stage.',
    icon: 'Gem',
    xpReward: 110,
    unlockRule: 'complete_section:Diamond Stage',
  },
  {
    id: 'dragon-slayer',
    name: 'Dragon Slayer',
    description: 'Defeat the Ender Dragon and complete the main questline.',
    icon: 'Swords',
    xpReward: 200,
    unlockRule: 'complete_task:defeat-dragon',
  },
];
